name: Test E2E

on:
  push:
    paths:
      - "nextjs/**"
defaults:
  run:
    working-directory: nextjs

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nextjs
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install --production=false
      - name: Docker Compose Build
        run: npm run docker:e2e:build
      - name: Docker Compose Up As E2E Testing
        run: npm run docker:e2e:ci
